## IRIS Dataste 활용 분류
---

In [92]:
# 모듈 로딩 ------------------------------------------
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np

### [1] 데이터 로딩 및 확인

In [140]:
# return_X_y => X => 특징들,데이터 , y => 라벨, 타겟
data, target = load_iris(as_frame=True, return_X_y=True)

type(iris), type(data), type(target)

(tuple, pandas.core.frame.DataFrame, pandas.core.series.Series)

In [141]:
print(data.info(), data.head(3), sep='\n\n')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
None

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2


In [142]:
print(target.head(3), target.unique(), target.value_counts(), sep='\n\n')

0    0
1    0
2    0
Name: target, dtype: int32

[0 1 2]

0    50
1    50
2    50
Name: target, dtype: int64


### [2] 학습 데이터 준비

In [143]:
# 데이터 => petal_length (cm), petal_width (cm)
# 타  겟 => 0, 2  
data = data.loc[:, data.columns[2:]]

print('data => ', data.shape)
print('target => ', target.shape)

data =>  (150, 2)
target =>  (150,)


In [144]:
# ------------------------------------------------

In [145]:
data.drop(range(50, 100), inplace=True)
target.drop(range(50, 100), inplace=True)

In [146]:
# 학습용 , 테스트용 데이터 분리
from sklearn.model_selection import train_test_split

In [147]:
# train:test=75%:25%
# test_size=0.X
# stratify => 분류 항목 비율 맞추어서 데이터셋 설정
# random_state => 매번 동일하게 데이터 구성하는 경우 지정
train_X, test_X, train_y, test_y = train_test_split(data,
                                                    target,
                                                    test_size=0.2,
                                                    stratify=target,
                                                    random_state=4)

In [148]:
print(train_X.shape, test_X.shape)
print(train_y.value_counts(), test_y.value_counts())

(80, 2) (20, 2)
0    40
2    40
Name: target, dtype: int64 0    10
2    10
Name: target, dtype: int64


In [165]:
# 모델 생성 학습
model = LogisticRegression()

In [166]:
# 학습
model.fit(train_X.values, train_y)

LogisticRegression()

In [167]:
# 학습 후 설정된 속성
print("분류 종류 : ", model.classes_)
print("가중치 값 : ", model.coef_)
print("절 편  값 : ", model.intercept_)
print("특성 갯수 : ", model.n_features_in_)

분류 종류 :  [0 2]
가중치 값 :  [[1.87871631 0.84564202]]
절 편  값 :  [-7.34250753]
특성 갯수 :  2


In [168]:
# 평가 => score() 학습용 데이터 점수, 테스트용 데이터 점수

In [169]:
model.score(train_X.values, train_y)

1.0

In [170]:
# 테스트 => predict(): 새로운 데이터로 진행
preY = model.predict(train_X.values)

preY

array([0, 2, 0, 0, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2,
       0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0,
       0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2])

In [171]:
# 1개 데이터
preY = model.predict([[1, 1]])
print('예측결과 : ', preY)

예측결과 :  [0]


In [172]:
probaY = model.predict_proba([[1, 1]])
print('분류항목 : ', model.classes_)
print('예측확률 : ', probaY)

분류항목 :  [0 2]
예측확률 :  [[0.99022544 0.00977456]]


In [173]:
# 결정함수
model.decision_function([[1, 1]])

array([-4.6181492])