## Keras LIB
---
- Tensorflow 기반의 Keras 패키지
- 기본 데이터 Tensor 타입
- 모델을 직접 설계/생성 해야함!!!

In [256]:
## 모듈 로딩
import tensorflow as tf

In [286]:
from tensorflow.keras import Sequential   # 모델 담는 애?
from tensorflow.keras.layers import Dense
import numpy as np
from sklearn.datasets import load_iris

In [258]:
# from keras import Sequential
# from keras.layer import Dense

In [259]:
# import tensorflow
# tensorflow.__version__

### [1] 모델 구성

In [260]:
model = Sequential(name='HelloModel')  # 지금은 빈 통

In [261]:
# 첫 번째 층은 반드시 입력 정보 파라미터 설정 => input_shape=() 튜플, input_dim=숫자
l1 = Dense(10, activation='relu', input_shape=(5,))

In [262]:
# 각 노드(퍼셉트론, 유닛) : 10개 입력 / 출력 : 50개
l2=Dense(50, activation='relu')  # 다중분류

In [263]:
# 각 노드(퍼셉트론, 유닛) : 50 입력 / 출력 : 5개?
l3=Dense(5, activation='softmax')

In [264]:
model.add(l1)
model.add(l2)
model.add(l3)

In [265]:
## 모델 구성 확인 => summary()
model.summary()  # 설계도?

Model: "HelloModel"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_47 (Dense)            (None, 10)                60        
                                                                 
 dense_48 (Dense)            (None, 50)                550       
                                                                 
 dense_49 (Dense)            (None, 5)                 255       
                                                                 
Total params: 865
Trainable params: 865
Non-trainable params: 0
_________________________________________________________________


### [2] 모델 생성
---
- 손실함수, 최적화 기법, 성능평가항목 설정
- compile() 메서드
    * optimizer : string 타입의 최적화기법명 입력 또는 객체 <- 기본값 사용하지 않는 경우
    * loss : 손실함수로 string 타입의 이름 입력
        - 분류 : caregorical_crossentropy, sparse_categorical_crossentropy, binary_crossentropy
        - 회귀 : mean_squred_error, mean_absolute_error..
    * metrics : 모델 평가 항목
        - accuracy, mse, mae...

In [266]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

### [3] 학습
---
- fit() 메서드
    * 훈련용 데이터
    * 훈련용 타겟
    * epochs : 학습 횟수 (처음~끝까지)
    * batch_size : 한번 학습량 (기:32)
    * validation_split / validation_data=(,) : 검증 데이터 설정
    * callbacks : 이벤트처리 함수 목록 (예: 학습중단 이벤트, 모델 검증 및 저장 이벤트...)
    * verbose : 학습 과정 출력 여부 설정(기:True)

In [267]:
## 데이터 로딩
iris = load_iris()

In [268]:
data = iris.data
target = iris.target

In [269]:
print(data.shape, target.shape)

(150, 4) (150,)


In [270]:
data[:1]

array([[5.1, 3.5, 1.4, 0.2]])

In [271]:
target[:5], target[50:55], target[100:105]

(array([0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1]), array([2, 2, 2, 2, 2]))

In [272]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [273]:
# label=LabelEncoder()
# target_=label.fit(target).transform(target)

In [274]:
ohe=OneHotEncoder()
target_2=ohe.fit(target.reshape(-1,1)).transform(target.reshape(-1,1))

In [275]:
type(target_2)

scipy.sparse.csr.csr_matrix

In [276]:
target_3=target_2.toarray()
type(target_3), target_3[0], target_3[50], target_3[100], target_3.shape

(numpy.ndarray,
 array([1., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 1.]),
 (150, 3))

# [1] 모델 구성

In [277]:
model = Sequential(name='IRIS')

In [278]:
# 첫번째 층은 반드시 입력정보 파라미터 설정 => input_shape=() 튜플, input_dim=숫자
# 각 노드(퍼셋트론, 유닛) : 4개 입력 / 출력 : 1개
# 총 10개가 다음 층(Layer)의 입력
l1=Dense(10, activation='relu', input_shape=(4,))

In [279]:
# 각 노드(퍼셉트론, 유닛) : 10개 입력 / 출력 : 3개
# 총 3개 출력
l2=Dense(3, activation='softmax')

In [280]:
model.add(l1)
model.add(l2)

In [281]:
## 모델 구성 확인 => summary()
model.summary()

Model: "IRIS"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_50 (Dense)            (None, 10)                50        
                                                                 
 dense_51 (Dense)            (None, 3)                 33        
                                                                 
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________


# [2] 모델 생성

In [282]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# [3] 학습

In [283]:
model.fit(data, target_3, epochs=5)

Epoch 1/5
5/5 [==============================] - 0s 2ms/step - loss: 1.1975 - accuracy: 0.3333
Epoch 2/5
5/5 [==============================] - 0s 2ms/step - loss: 1.1811 - accuracy: 0.3333
Epoch 3/5
5/5 [==============================] - 0s 2ms/step - loss: 1.1657 - accuracy: 0.3333
Epoch 4/5
5/5 [==============================] - 0s 2ms/step - loss: 1.1557 - accuracy: 0.3333
Epoch 5/5
5/5 [==============================] - 0s 1ms/step - loss: 1.1444 - accuracy: 0.3333


# [4] 평가
---
- evaluate()메서드
- 테스트용 데이터로 진행

In [284]:
## 평가
model.evaluate(data, target_3)
# model.evaluate([[5.1, 3.5, 1.4, 0.2]])

5/5 [==============================] - 0s 2ms/step - loss: 1.1393 - accuracy: 0.3333


[1.1392645835876465, 0.3333333432674408]

# [5] 예측
---
- predict()

In [285]:
## 예측
model.predict([[5.1, 3.5, 1.4, 0.2]])

1/1 [==============================] - 0s 66ms/step


array([[0.24737492, 0.2917271 , 0.46089804]], dtype=float32)