## 퍼셉트론(Perceptron)
---
- 뉴런을 컴퓨터 프로그램화 한 클래스
- 단순한 구조의 분류(Classification) 모델
- AND, OR 문제 분류 성공
- XOR문제 분류 실패

In [89]:
from sklearn.linear_model import Perceptron
import numpy as np

### [1] AND 분류
---
x1 x2 y  
0  0  0  
1  0  0  
0  1  0  
1  1  1

In [90]:
# 데이터 준비
X1 = [[0., 0.], [1., 0.], [0., 1.], [1., 1.]]
y1 = [0, 0, 0, 1]

In [91]:
# 모델 객체 생성
andModel = Perceptron()

In [92]:
# 학습
andModel.fit(X1, y1)

Perceptron()

In [93]:
# 모델 객체 속성 출력 함수
def showAttribute(model):
    print(f'classes_ : {model.classes_}')
    print(f'coef_ : {model.coef_}')
    print(f'intercept_ : {model.intercept_}')
    print(f'n_iter_ : {model.n_iter_}')

In [94]:
showAttribute(andModel)

classes_ : [0 1]
coef_ : [[2. 2.]]
intercept_ : [-2.]
n_iter_ : 10


In [113]:
# 예측
pre_and = andModel.predict(X1)
pre_and

array([0, 0, 0, 1])

In [96]:
print(f'정답 : {y1}')
print(f'예측 : {pre_and}')

정답 : [0, 0, 0, 1]
예측 : [0 0 0 1]


In [97]:
from sklearn.metrics import accuracy_score

In [98]:
print(f'{accuracy_score(y1, pre_and)}')

1.0


### [2] OR 연산 분류
---
x1 x2 y  
0  0  0  
1  0  1  
0  1  1  
1  1  1

In [99]:
# 데이터 준비
X2 = [[0., 0.], [1., 0.], [0., 1.], [1., 1.]]
y2 = [0, 1, 1, 1]

In [100]:
# 모델 객체 생성
orModel = Perceptron()

In [101]:
# 학습
orModel.fit(X2, y2)

Perceptron()

In [102]:
# 모델 객체 속성 출력 함수
showAttribute(orModel)

classes_ : [0 1]
coef_ : [[2. 2.]]
intercept_ : [-1.]
n_iter_ : 7


In [112]:
# 예측
pre_or = orModel.predict(X2)
pre_or

array([0, 1, 1, 1])

In [104]:
print(f'{accuracy_score(y2, pre_or)}')

1.0


### [3] XOR 연산 분류
---
x1 x2 y  
0  0  0  
1  0  1  
0  1  1  
1  1  0

In [105]:
# 데이터 준비
X3 = [[0., 0.], [1., 0.], [0., 1.], [1., 1.]]
y3 = [0, 1, 1, 0]

In [106]:
# 모델 객체 생성
xorModel = Perceptron()

In [107]:
# 학습
xorModel.fit(X3, y3)

Perceptron()

In [108]:
# 모델 객체 속성 출력 함수
showAttribute(xorModel)

classes_ : [0 1]
coef_ : [[0. 0.]]
intercept_ : [0.]
n_iter_ : 6


In [111]:
# 예측
pre_xor = xorModel.predict(X3)
pre_xor

array([0, 0, 0, 0])

In [110]:
print(f'{accuracy_score(y3, pre_xor)}')

0.5
