In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
iris = load_iris()

In [3]:
data = iris.data

In [4]:
target = iris.target

In [7]:
data.shape, target.shape, type(data), type(target)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [11]:
model = LogisticRegression(max_iter=500)

In [12]:
model.fit(data, target)

LogisticRegression(max_iter=500)

In [15]:
# 선형계수 즉 기울기w ==> 특성 Feature 마다 곱하기
print('classes_ : ', model.classes_)
print('coef_ : ', model.coef_)
print('intercept_ : ', model.intercept_)

classes_ :  [0 1 2]
coef_ :  [[-0.42434519  0.96692807 -2.51720846 -1.07938946]
 [ 0.53499003 -0.32132698 -0.20620328 -0.94424639]
 [-0.11064484 -0.64560109  2.72341174  2.02363584]]
intercept_ :  [  9.85512128   2.23277161 -12.08789289]


In [29]:
data[145:]

array([[6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [30]:
new_data = [6.7, 3. , 5.2, 2.3]

ret = model.decision_function([new_data])
print(ret)

[[-5.65928705  1.60920009  4.05008696]]


In [37]:
from scipy.special import softmax

# y = aw1 + bw2 + cw3 + dw4 + b
values = []
for i in range(3):
    y = model.coef_[i][0]*new_data[0] +\
        model.coef_[i][1]*new_data[1] +\
        model.coef_[i][2]*new_data[2] +\
        model.coef_[i][3]*new_data[3] + model.intercept_[i]
    print('y = ', y, end = ' ')
    values.append(y)
arrValue = np.array(values)
#     print('softmax => ', np.round(softmax(y)))

y =  -5.659287048399767 y =  1.609200091042602 y =  4.050086957356793 

In [38]:
np.round(softmax(ret), 3)

array([[0.  , 0.08, 0.92]])